//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is generated again.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRPFarmod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class for finding localized strings, etc.
    /// </summary>
    // This class was automatically generated by the StronglyTypedResourceBuilder
    // class automatically generated via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen
    // again with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NRPFarmod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the CurrentUICulture property of the current thread for all
        ///   Resource allocations that use this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FarliamRound {
            get {
                object obj = ResourceManager.GetObject("FarliamRound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GithubRound {
            get {
                object obj = ResourceManager.GetObject("GithubRound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GithubRound_sel {
            get {
                object obj = ResourceManager.GetObject("GithubRound_sel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hand {
            get {
                object obj = ResourceManager.GetObject("Hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iLollekRound {
            get {
                object obj = ResourceManager.GetObject("iLollekRound", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PayList {
            get {
                object obj = ResourceManager.GetObject("PayList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PlayListModeAktive {
            get {
                object obj = ResourceManager.GetObject("PlayListModeAktive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] YT {
            get {
                object obj = ResourceManager.GetObject("YT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Finds a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] YT_Selected {
            get {
                object obj = ResourceManager.GetObject("YT_Selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
